//
// CourseInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CourseInfo: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var language: String?
    public var image: String?
    public var description: String?
    public var ownerId: Int?

    public init(id: Int? = nil, name: String? = nil, language: String? = nil, image: String? = nil, description: String? = nil, ownerId: Int? = nil) {
        self.id = id
        self.name = name
        self.language = language
        self.image = image
        self.description = description
        self.ownerId = ownerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case language
        case image
        case description
        case ownerId = "owner_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(ownerId, forKey: .ownerId)
    }
}

