//
// Item.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Item: Codable, JSONEncodable, Hashable {

    public var title: String
    public var description: String?
    public var id: Int
    public var ownerId: Int

    public init(title: String, description: String? = nil, id: Int, ownerId: Int) {
        self.title = title
        self.description = description
        self.id = id
        self.ownerId = ownerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case description
        case id
        case ownerId = "owner_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(id, forKey: .id)
        try container.encode(ownerId, forKey: .ownerId)
    }
}

