//
// KeywordValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KeywordValue: Codable, JSONEncodable, Hashable {

    public var code: String
    public var value: String
    public var language: String

    public init(code: String, value: String, language: String) {
        self.code = code
        self.value = value
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case value
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(value, forKey: .value)
        try container.encode(language, forKey: .language)
    }
}

