//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var isActive: Bool? = true
    public var isSuperuser: Bool? = false
    public var fullName: String?
    public var id: Int?

    public init(email: String? = nil, isActive: Bool? = true, isSuperuser: Bool? = false, fullName: String? = nil, id: Int? = nil) {
        self.email = email
        self.isActive = isActive
        self.isSuperuser = isSuperuser
        self.fullName = fullName
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case isActive = "is_active"
        case isSuperuser = "is_superuser"
        case fullName = "full_name"
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(isSuperuser, forKey: .isSuperuser)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

