//
// UtilsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UtilsAPI {

    /**
     Test Celery
     
     - parameter msg: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func testCeleryApiV1UtilsTestCeleryPost(msg: Msg, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Msg?, _ error: Error?) -> Void)) -> RequestTask {
        return testCeleryApiV1UtilsTestCeleryPostWithRequestBuilder(msg: msg).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Test Celery
     - POST /api/v1/utils/test-celery/
     - Test Celery worker.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - parameter msg: (body)  
     - returns: RequestBuilder<Msg> 
     */
    open class func testCeleryApiV1UtilsTestCeleryPostWithRequestBuilder(msg: Msg) -> RequestBuilder<Msg> {
        let localVariablePath = "/api/v1/utils/test-celery/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: msg)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Msg>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Test Email
     
     - parameter emailTo: (query)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func testEmailApiV1UtilsTestEmailPost(emailTo: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Msg?, _ error: Error?) -> Void)) -> RequestTask {
        return testEmailApiV1UtilsTestEmailPostWithRequestBuilder(emailTo: emailTo).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Test Email
     - POST /api/v1/utils/test-email/
     - Test emails.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - parameter emailTo: (query)  
     - returns: RequestBuilder<Msg> 
     */
    open class func testEmailApiV1UtilsTestEmailPostWithRequestBuilder(emailTo: String) -> RequestBuilder<Msg> {
        let localVariablePath = "/api/v1/utils/test-email/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "email_to": (wrappedValue: emailTo.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Msg>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
